# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rQvZe0ggVQkNP0ZfE_74qwKsH2UbefD

1. Write a Python program to sum all the items in a
"""

def sum_list(input_list):
    total = 0
    for item in input_list:
        total += item
    return total
numbers = [1, 2, 3, 4, 5]
print(sum_list(numbers))

"""2. Write a Python program to multiply all the items in a list."""

def multiply_list(input_list):
    result = 1
    for item in input_list:
        result *= item
    return result
numbers = [1, 2, 3, 4, 5]
print(multiply_list(numbers))

"""3. Write a Python program to get the largest number from a list."""

def largest_number(input_list):
    return max(input_list)
numbers = [10, 5, 20, 15, 25]
print(largest_number(numbers))

"""4. Write a Python program to get the smallest number from a list."""

def smallest_number(input_list):
    return min(input_list)
numbers = [10, 5, 20, 15, 25]
print(smallest_number(numbers))

"""5. Write a Python program to remove duplicates from a list."""

def remove_duplicates(input_list):
    unique_items = set(input_list)
    unique_list = list(unique_items)
    return unique_list
numbers = [1, 2, 3, 2, 4, 5, 6, 1]
print(remove_duplicates(numbers))

"""6. Write a Python program to check if a list is empty or not."""

def is_list_empty(input_list):
    return len(input_list) == 0
list1 = []
list2 = [1, 2, 3]
print(is_list_empty(list1))
print(is_list_empty(list2))

"""7. Write a Python function that takes two lists and returns True if they have at least one common member."""

def has_common_member(list1, list2):
    for item in list1:
        if item in list2:
            return True
    return False
list1 = [1, 2, 3, 4]
list2 = [4, 5, 6, 7]
print(has_common_member(list1, list2))

"""8. Write a Python program to print a specified list after removing the 0th, 4th and 5th elements."""

colors = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
def del_elements(colors):
  del colors[5]
  del colors[4]
  del colors[0]
  return colors
print(del_elements(colors))

"""9. Write a Python program to print the numbers of a specified list after removing even numbers from it."""

def remove_even_numbers(input_list):
    odd_numbers = [num for num in input_list if num % 2 != 0]
    return odd_numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(remove_even_numbers(numbers))

"""10. Write a Python program to shuffle and print a specified list."""

import random
def shuffle_list(input_list):
    random.shuffle(input_list)
    return input_list
my_list = [1, 2, 3, 4, 5]
shuffled_list = shuffle_list(my_list)
print(shuffled_list)

"""11. Write a Python program to generate all permutations of a list in Python."""

from itertools import permutations
def generate_permutations(input_list):
    perms = permutations(input_list)
    perm_list = list(perms)
    return perm_list
my_list = [1, 2, 3]
permutations_list = generate_permutations(my_list)
print(permutations_list)

"""12. Write a Python program to convert a list of characters into a string."""

def list_to_string(char_list):
    string = ''.join(char_list)
    return string
characters = ['a', 'b', 'c', 'd', 'e']
result_string = list_to_string(characters)
print(result_string)

"""13. Write a Python program to append a list to the second list."""

def append_list(first_list, second_list):
    first_list.extend(second_list)
    return first_list
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result_list = append_list(list1, list2)
print(result_list)

"""14. Write a Python program to check whether two lists are circularly identical."""

def are_circularly_identical(list1, list2):
    if len(list1) != len(list2):
        return False
    concatenated_list = list2 + list2
    if ''.join(map(str, list1)) in ''.join(map(str, concatenated_list)):
        return True
    else:
        return False
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 1, 2]
result = are_circularly_identical(list1, list2)
print(result)

"""15. Write a Python program to find the second smallest number in a list."""

def second_smallest(numbers):
    unique_sorted_numbers = sorted(set(numbers))
    if len(unique_sorted_numbers) >= 2:
        return unique_sorted_numbers[1]
    else:
        return "List is too short to find the second smallest number."
numbers = [5, 2, 8, 1, 6, 3]
result = second_smallest(numbers)
print(result)

"""16. Write a Python program to find the second largest number in a list."""

def second_largest(numbers):
    unique_sorted_numbers = sorted(set(numbers), reverse=True)
    if len(unique_sorted_numbers) >= 2:
        return unique_sorted_numbers[1]
    else:
        return "List is too short to find the second largest number."
numbers = [5, 2, 8, 1, 6, 3]
result = second_largest(numbers)
print(result)

"""17. Write a Python program to find common items in two lists."""

def find_common_items(list1, list2):
    common_items = set(list1) & set(list2)
    return list(common_items)
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
result = find_common_items(list1, list2)
print("Common items:", result)

"""18. Write a Python program to insert an element before each element of a list.

"""

def insert_before_each_element(input_list, element):
    result = [element] * (len(input_list) * 2 - 1)
    result[::2] = input_list
    return result
input_list = [1, 2, 3, 4]
element = "x"
result = insert_before_each_element(input_list, element)
print("Result:", result)

"""19. Write a Python program to convert a string to a list."""

import ast
color = "['Red', 'Green', 'White']"
print(ast.literal_eval(color))

"""20. Write a Python program to find all the values in a list that are greater than a specified number."""

list1 = [220, 330, 500]
list2 = [12, 17, 21]
print(all(x >= 200 for x in list1))
print(all(x >= 25 for x in list2))